# Generated by Django 5.0.1 on 2024-01-29 22:26

import team.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('team_pic', models.ImageField(default='team_pics/default.png', null=True, upload_to=team.models.Team.upload_image)),
            ],
        ),
    ]
