# Generated by Django 5.0.1 on 2024-01-29 22:38

import team.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_team_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_pic',
            field=models.ImageField(null=True, upload_to=team.models.Team.upload_image),
        ),
    ]
