# Generated by Django 5.0.1 on 2024-02-05 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_team_created_by'),
        ('workspace', '0010_alter_member_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workspace.member'),
        ),
    ]
