# Generated by Django 5.0.1 on 2024-01-29 22:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_project_teams_alter_project_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 29, 23, 38, 16, 709918)),
        ),
    ]
