# Generated by Django 5.0.1 on 2024-01-30 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_project_created_by_alter_project_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 30, 10, 13, 42, 55009)),
        ),
    ]
