# Generated by Django 5.0.1 on 2024-01-30 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_project_is_complete_alter_project_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 30, 10, 40, 22, 254838)),
        ),
    ]
