# Generated by Django 5.0.1 on 2024-02-05 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_alter_project_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='label_color',
            field=models.CharField(default='0xFFFFFFFF', max_length=25),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 5, 15, 38, 33, 121508)),
        ),
    ]
