# Generated by Django 5.0.1 on 2024-01-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('iewer', 'Viewer'), ('editor', 'Editor')], default='iewer', max_length=6),
        ),
    ]
