# Generated by Django 5.0.1 on 2024-01-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_alter_workspace_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workspace',
            old_name='no_of_members',
            new_name='no_of_members_allowed',
        ),
        migrations.AddField(
            model_name='workspace',
            name='current_no_of_members',
            field=models.IntegerField(default=0),
        ),
    ]
