# Generated by Django 5.0.1 on 2024-01-26 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0004_rename_no_of_members_workspace_no_of_members_allowed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['workspace']},
        ),
    ]
