# Generated by Django 5.0.1 on 2024-01-26 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0006_workspace_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='is_verified',
        ),
    ]
