# Generated by Django 4.1.13 on 2024-04-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0010_alter_member_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='plan',
            field=models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], default='basic', max_length=10),
        ),
    ]
