# Generated by Django 5.0.1 on 2024-01-26 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_blacklistedtoken_user_alter_blacklistedtoken_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlacklistedToken',
        ),
    ]
