# Generated by Django 5.0.1 on 2024-01-29 22:26

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_delete_blacklistedtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(default='profile_pics/default.png', null=True, upload_to=user.models.CustomUser.upload_image),
        ),
    ]
