# Generated by Django 5.0.1 on 2024-03-20 09:33

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(default='user/default.png', null=True, upload_to=user.models.CustomUser.upload_image),
        ),
    ]
