# Generated by Django 4.1.13 on 2024-04-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='subscription_plan',
            field=models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro'), ('ultimate', 'Ultimate')], default='starter', max_length=10),
        ),
    ]
